#         Powered by TabooLib 6.0         #


Database:
  enable: false
  host: localhost
  port: 3306
  user: root
  password: root
  database: minecraft
  prefix: zaphkiel

Durability:
  display: '&8[ &f%symbol% &8]'
  display-symbol:
    0: ◆
    1: ◇

SoulBind:
  enable: true
  lore: "灵魂绑定: %player%"
  deny-inventory: true
  deny-anvil: true
  deny-craft: true
  deny-pickup: true
  deny-drop: true
  deny-consume: true

